<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                                    => __DIR__ . '/Module.php',
    'Application\Controller\IndexController'                => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Entity\Commentaire'                        => __DIR__ . '/src/Application/Entity/Commentaire.php',
    'Application\Mapper\Commentaire'                        => __DIR__ . '/src/Application/Mapper/Commentaire.php',
    'Application\Mapper\CommentHydrator'                    => __DIR__ . '/src/Application/Mapper/CommentHydrator.php',
    'Application\Mapper\Exception\ExceptionInterface'       => __DIR__ . '/src/Application/Mapper/Exception/ExceptionInterface.php',
    'Application\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/Application/Mapper/Exception/InvalidArgumentException.php',
    'Application\Mapper\Exception\RuntimeException'         => __DIR__ . '/src/Application/Mapper/Exception/RuntimeException.php',
);
